### ISSUE TITLE
Build failure during ./scripts/MakeHeader.py

### ISSUE THREAD

**Issue by Earnestly** [hishamhm/htop#616]
* Python 3.6.1

Please consider using `python2` in your shebang instead of assuming version of `python` (explicit is better than implicit)

```
./scripts/MakeHeader.py Action.c
Traceback (most recent call last):
  File "./scripts/MakeHeader.py", line 4, in <module>
Traceback (most recent call last):
  File "./scripts/MakeHeader.py", line 4, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/MakeHeader.py", line 6, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/MakeHeader.py", line 6, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
make: *** [Makefile:2384: Panel.h] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:2384: Action.h] Error 1
```

Current working around: `sed -i '1 s/python$/&2/' scripts/MakeHeader.py`.

**Comment by rindeal** [comment]
fixed in https://github.com/hishamhm/htop/commit/4300a19592a8f1e5c781587441fd5ddbc26d396d

**Comment by Earnestly** [comment]
Thanks, builds fine here now o/
